# Generated by Django 2.2.2 on 2019-06-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
